version: '3.8'
services:
  selenium-hub:
    image: selenium/hub:4.15.0
    ports:
      - 4444:4444
      - 4442:4442
      - 4443:4443
  
  node-chrome:
    image: selenium/node-chrome:119.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - TZ=Asia/Tokyo
      - HUB_HOST=selenium-hub
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  
  script-runner-chrome:
    image: whoatemyapplepie/script-runner-chrome:0.1.0
    build:
      context: ./script_runner_chrome
    volumes:
      - ./script_runner_chrome:/app
    depends_on:
      - selenium-hub
    tty: true
    environment:
      - HUB_HOST=selenium-hub
      - BROWSER_NAME=chrome